// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrations run over the direct (non-pooled) connection; the app runtime
  // uses the pooled DATABASE_URL via the driver adapter.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
